version: '3.9'
name: cpool-leak
services:
  db:
    image: postgres:16.6
    environment:
      POSTGRES_DB: cpool-leak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
